---
- name: Register RHEL 9 with an activation key
  hosts: rhel9
  tasks:
    - name: Register RHEL 9 with an activation key
      community.general.redhat_subscription:
        state: present
        activationkey: Nassri-123
        org_id: 11009103
    - name: Set hostname
      ansible.builtin.hostname:
        name: Rhel9.demo.redhat.com
