---
- name: Register RHEL 9 with activationkey
  hosts: all
  tasks:
    - name: Register RHEL 9 with activationkey
      community.general.redhat_subscription:
        state: present
        activationkey: Nassri-123
        org_id: 11009103
        auto_attach: true
    - name: Configure hostname
      ansible.builtin.hostname:
        name: rhel9.demo-lisbon.redhat.com
