---
- name: register server with subscription-manager and set hostname
  hosts: rhel9
  tasks:
    - name: register with subscription-manager
      community.general.redhat_subscription:
        state: present
        activationkey: Nassri-123
        org_id: 11009103
    - name: set hostname
      ansible.builtin.hostname:
        name: rhel9.demo-lx.redhat.com
    - name: install firewalld service 
      ansible.builtin.package:
        name: firewalld
        state: present
    - name: start firewall service 
      ansible.builtin.service:
        name: firewalld
        state: started
    - name: install cockpit service 
      ansible.builtin.package:
        name: cockpit
        state: present
    - name: enable cockpit service 
      ansible.builtin.service:
        name: cockpit
        state: started
        enabled: true
    - name: enable cockpit service in firewall 
      ansible.posix.firewalld:
        service: cockpit
        permanent: true
        state: enabled


