---
- name: subscription-manager module demo
  hosts: rhel9
  tasks:
    - name: configure subscription
      community.general.redhat_subscription:
        state: present
        activationkey: Nassri-123
        org_id: 11009103
    - name: set hostname
      ansible.builtin.hostname:
        name: rhel9.demo-lx.redhat.com
    - name: install firewall service 
      ansible.builtin.package:
        name: firewalld
        state: present
    - name: enable firewall service 
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true


