---
- name: register server with activation key and configure hostname
  hosts: rhel9
  tasks:
    - name: register with activationkey
      community.general.redhat_subscription:
        state: present
        activationkey: Nassri-123
        org_id: 11009103
    - name: configure hostname
      ansible.builtin.hostname:
        name: rhel9.demo-lx.redhat.com
