---
- name: subscription-manager module demo
  hosts: rhel9
  tasks:
    - name: register with subscription-manager
      community.general.redhat_subscription:
        state: present
        activationkey: Nassri-123
        org_id: 11009103
    - name: set hostname
      ansible.builtin.hostname:
        name: rhel9.demo-lisbon.redhat.com
