---
- name: register server with activation key and configure hostname
  hosts: rhel9
  tasks:
    - name: register with activationkey
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ _activationkey_ }}"
        org_id: ExampleOrg
    - name: configure hostname
      ansible.builtin.hostname:
        name: rhel9.demo-lisbon.redhat.com
    - name: install firewall service  
      ansible.builtin.package:
        name: firewalld
        state: present
    - name : enable firewall service 
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started
    - name : install httpd service 
      ansible.builtin.package:
        name: httpd
        state: present
    - name : install cockpit service 
      ansible.builtin.package:
        name: cockpit
        state: present
    - name : enable httpd and cockpit service 
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - httpd
        - cockpit
    - name: update all packages via dnf  
      ansible.builtin.package:
        name: '*'
        state: latest










    


  
