---
- name: Set rhel9.demo.redhat.com hostname
  hosts: rhel9
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: rhel9-new.demo.redhat.com
    - name: Register rhel server with org and activation key 
      community.general.redhat_subscription:
        state: present
        org_id: 11009103
        activationkey: Nassri-123
    - name: install cockpit service 
      ansible.builtin.package:
        name: cockpit
        state: latest
    - name: install ntpd service for rhel9 
      ansible.builtin.package:
        name: chrony
        state: latest
    - name : start cockpit service 
      ansible.builtin.service:
        name: cockpit
        state: started
        enabled: true
    - name : start firewall service 
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
    - name : enable cockpit service on firewall 
      ansible.posix.firewalld:
        service: cockpit
        permanent: true
        state: enabled
    - name : configure ntp service to use time.cloudflare.com 
      ansible.builtin.lineinfile:
        path: /etc/chrony.conf
        line: server time.cloudflare.com iburst
        insertafter: ^server.*
    - name : restart ntp service 
      ansible.builtin.service:
        name: chrony
        state: restarted
    - name: add users sandra and nassri 
      ansible.builtin.user:
        name: "{{ item }}"
      loop:
        - sandra
        - nassri
        - john
    - name : force users to change password  on the 1st login from 1234ABC to new password 
      ansible.builtin.shell:
        cmd: usermod --password $(openssl rand -base64 32) {{ item }}
      loop:
        - sandra
        - nassri
        - john

      






      








