---
- name: Register RHEL 9 with an activation key and org id
  hosts: all
  tasks:
    - name: Register RHEL 9 with an activation key and org id
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ Nassri-123 }}"
        org_id: 11009103
        auto_attach: true
        force_register: true
    - name: Configure hostname
      ansible.builtin.hostname:
        name: rhel9.demo-lisbon.redhat.com
