---
- name: Set rhel9.demo.redhat.com hostname
  hosts: rhel9
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: rhel9-new.demo.redhat.com
    - name: Register rhel server with org and activation key 
      community.general.redhat_subscription:
        state: present
        org_id: 11009103
        activationkey: Nassri-123
    - name: install cockpit service 
      ansible.builtin.package:
        name: cockpit
        state: latest
    - name : start cockpit service 
      ansible.builtin.service:
        name: cockpit
        state: started
        enabled: true







