---
- name: A simple playbook to configure a host
  hosts: rhel9
  vars:
    services:
      - cockpit
      - firewalld
      - httpd 
  tasks:
    - name: Register system in Red hat with org ID and activation key
      community.general.redhat_subscription:
        state: present
        org_id: 11009103
        activationkey: Nassri-123
    - name: Configure hostname and FQDN
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
        use: systemd
    - name: Configure dns server to 1.1.1.1
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        line: DNS=1.1.1.1
        regexp: ^DNS=
    - name: install services 
      ansible.builtin.package:
        name: "{{ services }}"
        state: present




      
    
