---
- name: Register RHEL 9 with activation key and configure hostname
  hosts: all
  tasks:
    - name: Register RHEL 9 with activation key
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ Nassri-123 }}"
        org_id: 11009103
        auto_attach: true
    - name: Configure hostname
      ansible.builtin.hostname:
        name: rhel9.demo-lisbon.redhat.com
