---
- name: Register RHEL 9 with activationkey
  hosts: all
  vars:
    activationkey:
      - Nassri-123
  tasks:
    - name: Register RHEL 9 with activationkey
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ activationkey }}"
        org_id: 11009103
    - name: Configure hostname
      ansible.builtin.hostname:
        name: rhel9.demo-lisbon.redhat.com
