---
- name: register server with activation key and configure hostname
  hosts: rhel9
  tasks:
    - name: register with activationkey
      community.general.redhat_subscription:
        state: present
        activationkey: Nassri-123
        org_id: 11009103
    - name: configure hostname
      ansible.builtin.hostname:
        name: rhel9.demo-lx.redhat.com
    - name: install firewall service  
      ansible.builtin.package:
        name: firewalld
        state: latest
    - name: enable firewall service 
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
    # install httpd service & enable httpd service 
    - name: Install httpd service
      ansible.builtin.package:
        name: httpd
        state: latest
    - name: Enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

