---
- name: Register RHEL 9 with an activation key
  hosts: rhel9
  tasks:
    - name: Register RHEL 9 with an activation key
      community.general.redhat_subscription:
        state: present
        activationkey: Nassri-123
        org_id: 11009301  
    - name: Set hostname
      ansible.builtin.hostname:
        name: rhel9.demo.redhat.com
    - name: install firewall service
      ansible.builtin.package:
        name: firewalld
        state: present
    - name: start firewall service
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

