---
- name: Register RHEL 9 with an activation key
  hosts: all
  tasks:
    - name: Register RHEL 9 with an activation key
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ _activationkey_ }}"
        org_id: Example
        auto_attach: true
    - name: Set hostname
      ansible.builtin.hostname:
        name: Rhel9.demo.redhat.com
    - name: install firewall service
      ansible.builtin.package:
        name: firewalld
        state: present
    - name: enable Firewall service 
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

