---
- name: Register RHEL 9 with activationkey and also set hostname
  hosts: rhel9
  tasks:
    - name: Register RHEL 9 with activationkey
      community.general.redhat_subscription:
        state: present
        activationkey: Nassri-123
        org_id: 11009103
    - name: Set hostname
      ansible.builtin.hostname:
        name: rhel9.demo.redhat.com
    - name: install firewall service
      ansible.builtin.package:
        name: firewalld
        state: present
