---
- name: subscription-manager module demo
  hosts: rhel9
  tasks:
    - name: configure subscription
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ _activationkey_ }}"
        org_id: ABCDEFGH
        auto_attach: true
    - name: set hostname
      ansible.builtin.hostname:
        name: rhel9.demo-lx.redhat.com
